from DatabaseManager import DBmanager
from queue import Queue
#A rough draft of the code below
"""
The advising manager will generate a few linked list based on the users curriculums.
Have the course linekd list point to a course in the linked list in order to (X-prerequisites could be the previous course Ex: 250 prereq=csdp 222)

for example csdp: [100]->[221]->[222]->[250]->[301]->...
                           |
                           V
                   math:[109?]-[110]
each node will be the courses informatiion, (courseID, course,name, number, title, requisites, priority, and pass-condition(either pass/withdraw/failed?))
These list will be generated by curriculum area ex: csdp 221<= program core, csdp
                                                    math 109 >= curriculum iv(Mathematics)
                                                    math 112 <= program core, math
program core must have priority over other courses
priority needs an symbolic representation with !
Prerequisites: -
Co-requisites: ~ 

"""


class Course:
    def __init__(self, dataval=[]):
        self.CourseID=dataval[0]
        self.course=dataval[1]
        self.number=dataval[2]
        self.title=dataval[3]
        self.credits=dataval[4]
        self.Status="X" #Status represents three symbols P=pass, F=failed, W=withdrawal, E=enrolled,~=for Don't need to take ,X=for nonselected 
        self.nextval=None
class CourseList:
    def __init__(self,Listname:str):
        self.totalscore=0
        self.Listname=Listname
        self.headval=None
    def getCourse(self,dataval:Course):
        newCourse=dataval
        if (self.headval is None):
            self.headval=newCourse
        else:
            curr=self.headval
            while(curr.nextval is not None):
                curr=curr.nextval
            curr.nextval = newCourse
       
    def PrintList(self):
        curr=self.headval
        message=""
        if(curr!=None):
            print(f"{self.Listname}:")
            while(curr is not None):
                message+=str(curr.title)+"->"
                curr=curr.nextval
            message+="NULL"
        else:
            message+="N/A"
        print(message)
        
    def Search(self, target:Course):
        curr=self.headval
        if(curr!=None):
            while(curr is not None):
                if(curr.CourseID in target.CourseID):
                    return True
                curr=curr.nextval
        return False

class Student: #This class will have the structured set of information of students
    def __init__(self):
        self.Name=""
        self.StudentID=""
        self.totalcredit=None
        self.Major=""
        self.Courses={}
        self.CourseHistory={}
    def addCourses(self,NewCourse:Course):
        CourseName=str(NewCourse.title).upper()
        if(self.Courses==[]):
            NewCourseTree=CourseList(CourseName)
            NewCourseTree.getCourse(NewCourse)
            self.Courses.append(NewCourseTree)
        else:
            existingArea=False
            #Check if there is an existing course list with the same course abrev. 
            #if so, either insert course in existing course list or if the courselist doesn't exist
            for i in self.Courses:  
                if i.ListName == NewCourse.course:
                    existingArea=True
                    if(i.Search(NewCourse)==False):
                        i.GetCourse(NewCourse)
                    break
            if(existingArea==False):
                NewCourseTree=CourseList(CourseName)
                NewCourseTree.getCourse(NewCourse)
                self.Courses.append(NewCourseTree)
                

if __name__ in "__main__":
    A = DBmanager("localhost", "root", "1234","hawkdb")
    Courses={}
    CourseABVList=[]
    for i in range(len(A.tables[0].Content)):
        NewCourse=Course(A.tables[0].Content[i])
        CourseAbv=str(NewCourse.course).upper()
        if(CourseAbv not in CourseABVList):
            CourseABVList.append(CourseAbv)
            NewCourseTree=CourseList(CourseAbv)
            NewCourseTree.getCourse(NewCourse)
            Courses[CourseAbv]=NewCourseTree
        else:
            Courses[CourseAbv].getCourse(NewCourse)

        
    for value in Courses.values():
        value.PrintList()
          
    """
    A = DBmanager("localhost", "root", "1234","hawkdb")
    Courses=[]
    for i in range(len(A.tables[0].Content)):
        NewCourse=Course(A.tables[0].Content[i])
        CourseName=str(NewCourse.title).upper()
        if(Courses==[]):
            NewCourseTree=CourseList(CourseName)
            NewCourseTree.getCourse(NewCourse)
            Courses.append(NewCourseTree)
        else:
            existingArea=False
            #Check if there is an existing course list with the same course abrev. 
            #if so, either insert course in existing course list or if the courselist doesn't exist
            for i in Courses:  
                if i.Listname == NewCourse.course:
                    existingArea=True
                    if(i.Search(NewCourse)==False):
                        i.GetCourse(NewCourse)
                    break
            if(existingArea==False):
                NewCourseTree=CourseList(CourseName)
                NewCourseTree.getCourse(NewCourse)
                Courses.append(NewCourseTree)
    for i in Courses:
        i.PrintList()
"""
"""
    Code below is testcase of getting all the courses and set them in a course tree.
    A = DBmanager("localhost", "root", "1234","hawkdb")
    CourseTree=CourseList("CSDP")
    for i in range(len(A.tables[0].Content)):
        NewCourse=Course(A.tables[0].Content[i])
        #if ("CSDP" in str(A.tables[0].Content[i][1])):
        CourseTree.getCourse(NewCourse)
    CourseTree.PrintList()
"""
